-- 네이버 영화검색 결과 저장용 테이블 생성 스크립트
-- table.sql
DROP TABLE MOVIE CASCADE CONSTRAINTS;

CREATE TABLE MOVIE (
    RANK NUMBER PRIMARY KEY,
    TITLE VARCHAR2(300) NOT NULL,
    PERSONS VARCHAR2(100) NOT NULL,
    LINK VARCHAR2(4000) NOT NULL,
    IMG_PATH VARCHAR2(4000) NOT NULL
)