_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.0
            "8":
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
env_name:
    value: MountainCarContinuous-v0
episode_reward_avg_solved:
    value: 85
gamma:
    value: 0.9
learning_rate:
    value: 0.0005
max_num_episodes:
    value: 200000
print_episode_interval:
    value: 20
train_num_episodes_before_next_test:
    value: 100
validation_num_episodes:
    value: 3
